### ISSUE TITLE
links for videos

### ISSUE THREAD

**Issue by etosch** [UMassGradReps/umassgradreps.github.io#19]
Hi Rick,
The talks can be found here: 
http://podserv.cs.umass.edu/groups/facultytalks/ You will need to log in 
with your CICS account to view them.
Rob

**Comment by etosch** [comment]
@UMassGradReps/current-grad-reps Can you take a look at the Resources tab and let me know what you think of how we're presenting this information?

**Comment by strubell** [comment]
lgtm
